; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
$SG2583	DB	'Hey. What''s up?', 0aH, 00H
	ORG $+3
$SG2584	DB	'%s', 00H
_DATA	ENDS
PUBLIC	main
EXTRN	printf:PROC
pdata	SEGMENT
$pdata$main DD	imagerel $LN3
	DD	imagerel $LN3+30
	DD	imagerel $unwind$main
pdata	ENDS
xdata	SEGMENT
$unwind$main DD	010401H
	DD	04204H
; Function compile flags: /Odtp
xdata	ENDS
_TEXT	SEGMENT
main	PROC
; File c:\program files (x86)\microsoft visual studio 10.0\vc\bin\amd64\hellos.c
; Line 2
$LN3:
	sub	rsp, 40					; 00000028H
	lea	rdx, OFFSET FLAT:$SG2583
	lea	rcx, OFFSET FLAT:$SG2584
	call	printf
	xor	eax, eax
	add	rsp, 40					; 00000028H
	ret	0
main	ENDP
_TEXT	ENDS
END
