; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
$SG80334 DB	'Hey!', 00H
	ORG $+3
$SG80335 DB	'What''s Up?', 00H
_DATA	ENDS
PUBLIC	main
EXTRN	__imp_MessageBoxA:PROC
pdata	SEGMENT
$pdata$main DD	imagerel $LN3
	DD	imagerel $LN3+36
	DD	imagerel $unwind$main
pdata	ENDS
xdata	SEGMENT
$unwind$main DD	010401H
	DD	04204H
; Function compile flags: /Odtp
xdata	ENDS
_TEXT	SEGMENT
main	PROC
; File c:\program files (x86)\microsoft visual studio 10.0\vc\bin\amd64\msgbox.c
; Line 2
$LN3:
	sub	rsp, 40					; 00000028H
	xor	r9d, r9d
	lea	r8, OFFSET FLAT:$SG80334
	lea	rdx, OFFSET FLAT:$SG80335
	xor	ecx, ecx
	call	QWORD PTR __imp_MessageBoxA
	xor	eax, eax
	add	rsp, 40					; 00000028H
	ret	0
main	ENDP
_TEXT	ENDS
END
